twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/assets': images
        '%kernel.project_dir%/public/assets/css': email
    form_themes: ['bootstrap_4_layout.html.twig']
